### PR TITLE
Support for callbacks injected before default handlers

### PR DESCRIPTION
**Pull request by ian-h-chamberlain**
Building on #35, this PR makes some changes to inject the custom callback _before_ the default watcher handlers, which allows the callback to make some changes to the values before they are returned to the client.

Additionally, I simplified the callback example and removed the threading code from it to make it easier to understand how the callback is invoked. Manually testing all of the included examples and integration tests resulted in success for both python2.7 and python3.6.

Not sure whether this repo is still being actively maintained but I figured I'd open a new PR since the original went kind of stale. Let me know if there are any additional changes / checks needed before this can be merged.

### CODE REVIEW

**Comment by pief** [comment]
Thank you for your MR, it is definitely still maintained, but I have to look at it. Plan to do so the next days.

**Comment by pief** [comment]
So I looked at the underlying changes implementing new vartypes and decided that variables types in general were not implemented "the right way" (TM). For example, tests were missing which made me find a larger bug in the IPAddress var type (fixed in master now). But also the implementation of var types so far as such.

So I decided to rewrite them, ongoing work that can be seen in the ``rewrite_vartypes`` branch. I'm currently porting the underlying additional vartypes to them, so I can also close billr's MR, then I'll have a look to see how your code and callback handlers fit in there. But the feature as such is definitely coming into master, probably this or next week already.

**Comment by ian-h-chamberlain** [comment]
Ok sounds good! Let me know if you want me to update this PR once those changes are in - I expect there will be some conflicts and I will presumably need to remove those commits from this branch.

Thanks for looking at it!

**Comment by pief** [comment]
I've rebased your changes on current master and did some minor editorial stuff (applied your whitespace fixes directly to Bill's commits) in the ``callbacks`` branch. I'll look a bit furter in more detail now and will possibly squash them together, not sure yet. I'll keep you posted.

**Comment by pief** [comment]
Merged through 951eb1b2

**Comment by pief** [comment]
I'm afraid I had to force undo the merge.

One reason is that the example callback agent imports everything from the `netsnmpapi` module -- it is not supposed to do that. `netsnmpagent` is supposed to be the interface to Python programs with `netsnmpapi` only being used internally. If client code begins importing `netsnmpapi` and we tolerate that, we will enter hell as we will never be able to change internals.

I'm also not convinced that directly mapping net-snmp C API structures 1:1 via ctypes and exposing that to Python applications is the right way forward but I have to think about it.

For these reasons I'm reopening this.

**Pull request closed without merging**
