### PR TITLE
Send traps and callback added

### PR DESCRIPTION
**Pull request by jbize**
Hello,

My remote master branch is current with your master and can be automatically merged.

I have added callbacks and they work with table row/cell data.

I have added send traps and it is Python3 compliant.

I also added a few convenience methods, and addressed an issue in which a TableRow becomes stale following an snmpset to any column in the row.  I added a row/column update method to the table itself.  This avoids memory errors working with the stale row.

This code runs under python 3.7 and 3.8, as well as 2.7.

I am currently using this to develop production code for a client's product.

I hope you will consider accepting this pull request.

### CODE REVIEW

**Comment by pief** [comment]
Gradually working myself through PRs now

**Comment by jbize** [comment]
Pieter,

My pull request included send_trap and callbacks and was current with
your master.  I did all the work for you.

John

**Comment by pief** [comment]
Ok, I looked through your MR and I will not merge it in this state for a number of reasons. Here's why:
- you included code from other open MRs and merged them into yours, probably trying to offer me a "one stop" solution, but development doesn't work that way. MRs are generally supposed to address *one* feature or concern, so we don't have to undo three things at once if one of them breaks. Thus a specific commit fixing an issue with other MRs should have gone on a copy of that MR's branch, adding the commit on top of it and offered as a separate MR. Yes, that's cumbersome, but that's how things are. 
- commit messages were partially non-descriptive: `fixed missing variable error`. Where/in which module? With a message like this I'd have to look at the actual commit and can not deduce from looking at the commit history alone that e.g. this could be a commit affecting module X if I'm debugging which recent change broke module X. My commit messages here usually include "netsnmpagent" or "netsnmpapi" so I can see at once that a change is specific to that Python module. Whereas a a more generic message such as "Bump copyright year" suggests that multiple files are affected/the list of files is too long for the commit subject line. Sometimes however I may also just have been too lazy as with "Update README". That's ok with my own project because I can stand my lazyness, but if I were to submit that commit to a different project, they'd probably reject it.
- in general commit messages should conform to the general Git commit message formatting rule of "first line = brief description, empty line, detailed description". A detailed description should not so much describe the _what_ but the _why_ of the change because otherwise one can only guess the intent. One example is your first commit "update git ignore and file modes" where you add `.project` and `.pydevproject` to `.gitignore´ but you don't explain why to add these files. My guess is that your editor created those but then what do these have to do in a global code repository where people use different editors? What's the benefit of other users or developers if this change gets merged unless by chance they happen to use exactly the same editor as you do? Same for the file mode change: one can _guess_ why you did that but one can't _know_ it.
- "cb example runs, but still need to handle cp on table objects" is not a Git commit description, it's an internal remark you made for yourself. If I review the MR, you implicitly require me to walk the commits after this to see if one of them "handles cp on table objects" which requires additional time. Now I see there's a commit "got the callbacks on table columns working" which makes me think: so why didn't he squash the two into one commit? If that second seems to fix something not yet addressed in the first commit, and both haven't gone upstream yet, it makes sense to combine them into one and it's also tidier.
- you have five merge commits where you merged your `sendtrap_callback` branch into your `master` branch. Is this supposed to be reflected 1:1 in the upstream repository's history? Surely not. This is exactly one of the things that one usually cleans up via `git rebase -i` before one submits a MR. Also one sees this and asks _but why?_: why did the developer merge all the time to his master branch if the feature branch wasn't ready yet?

Note that these were formal reasons so far. As for the actual content of the changes, I naively merged the separate MR with callback support today but I just had to undo that in a nasty and not-nice way, for the reasons laid out in https://github.com/pief/python-netsnmpagent/pull/38. This is a prime example of where I as a maintainer and sort-of architect of python-netsnmpagent have to reject "easy" looking implementations that have consequences that the submitter is not aware of or judges differently. I inadvertently thought it can't be that bad to merge it but it _is_ bad. Callback support requires a second thought.

The same probably applies to SNMP trap support as well. I'd have to look at it in detail, that's _my_ job and neither you nor anyone else can do that for me. And prioritywise I'll of course prefer reviewing fixes to new functionality. Having said that, there are certainly some fixes in your MR that I most definitely will want to include. However, because they're hidden in one big pile, I'll extract and apply them individually now.

One final note (in this MR): this is not a "piss off" message. If it were that, I wouldn't have gone into great detail to explain the reasons why I can't merge this as-is. It's also not a verdict of missing appreciation. Of course I appreciate if code I wrote isn't totally useless and even more so if engagement is not only done message-wise but also in form of concrete code, but like other projects I can't sacrifice development standards, even if I have little time for the project on the side and no one's paying me for development.

As I said, I'll now myself first try to identify and extract the "Low hanging fruit"; things that can applied very quickly, e.g. bugfixes, and of course you'll be given credit for that.

**Comment by jbize** [comment]
Pieter,

I needed these features (send_trap and callbacks) three weeks ago.  I
also needed it to run under Python 3 and have a few extra methods to
support extending the callbacks for processing SNMP sets.  You had
indicated that this was a low priority for you, so I added them to my
fork. I was in a hurry and was developing on one machine and testing on
another.  That is the reason for all the crazy commits. 

After I finished and tested everything, mostly in my sub-agent, I wanted
to offer it back as-is so that you wouldn't face the same struggles I did. 

John

**Pull request closed without merging**
