### PR TITLE
Fix packaging of examples

### PR DESCRIPTION
**Pull request by csdexter**
- the proper destination is %{_defaultdocdir}/%{name}-%{version} ...
  - ... but why bother when %doc can magically take care of it?

### CODE REVIEW

**Comment by csdexter** [comment]
Hello, thanks for including RPM packaging in your build scripts so that a simple `make rpms` gives you a shiny RPM that you can just `yum localinstall` in your system :)

I noticed your `.spec` file was putting the `examples/` folder in the wrong location so I prepared this pull request to fix it. I only have access to CentOS machines so you may want to test this on SuSE as well.

Thanks!

**Comment by pief** [comment]
Well, it doesn't work on SUSE :)

What exactly is your issue on CentOS? Did the RPM not build or did it build, but the path is not correct?

**Comment by pief** [comment]
I correct, it does seem to work.

**Comment by csdexter** [comment]
I'm happy to hear it works on SuSE too :)

The RPM did get built, but the example files ended up in `/usr/share/doc/python-netsnmpagent` instead of `/usr/share/doc/python-netsnmpagent-<version number>` as they should have and as the other documentation files (like `README` etc.) did.

Thanks for accepting this pull request, I'll probably be sending more in the days to come as I've started using your library in a project and I'd love to give something back by contributing.

**Pull request merged**
